[package]
name = "dod-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.11.1"
criterion = "0.3"

[[bench]]
name = "parse_benchmark"
harness = false
